### ISSUE TITLE
Capitalization changes have unexpected effects

### ISSUE THREAD

**Issue by MeWhenI** [RockstarLang/rockstar#363]
```
rock array with 100
say array at 0 (prints: 100)
say Array at 0 (prints: 100)
say array At 0 (prints: 100)
say Array At 0 (prints: mysterious)
```
The parse tree for this code shows that Rockstar interprets the last line differently because it identifies `Array At` as the name of a proper variable. This seems bad probably.

Parse tree:
```
enlist
  variable: array
  100
output: 
  lookup: array[0]
output: 
  lookup: Array[0]
output: 
  lookup: array[0]
output: 
  lookup: Array At
expression_statement:
  0
```
